---

# The Data Manager Kubernetes name
# (used as a suffix for the namespace unless it's explicitly named)
jo_dmapi_name: integration
jo_dmapi_namespace: data-mamager-api
jo_image_tag: 1.3.1

# The Kubernetes config file
jo_kubeconfig: ~/k8s-config/config-local
