---

# The Data Manager Kubernetes name
# (used as a suffix for the namespace unless it's explicitly named)
jo_dmapi_name: integration
jo_dmapi_namespace: data-manager-api
jo_image_tag: 1.4.0
jo_namespaces: data-manager-api

# The Kubernetes config file
jo_kubeconfig: ~/k8s-config/config-local
