---

# Operator state?
# One of 'present' or 'absent'
jo_state: present

# The kubernetes config file.
jo_kubeconfig: SetMe

# The Operator container image and tag
jo_image: informaticsmatters/data-manager-job-operator
jo_image_tag: SetMe
# The colon-separated list of namespaces
# we want the CRD to be used with.
jo_namespaces: data-manager-api-integration

# The name (and namespace) of the Data Manager API.
# The namespace is where the operator will be located,
# and is expected to exist.
jo_dmapi_name: integration
jo_dmapi_namespace: data-manager-api-{{ jo_dmapi_name }}

# Job pod node selection.
# Jobs will be run on nodes that have labels keys and values defined here...
jo_pod_node_selector_key: informaticsmatters.com/purpose-worker
jo_pod_node_selector_value: 'yes'

# The pre-delete delay (seconds) for Pods.
# After a Pod's finished it's deleted after this period has elapsed.
jo_pre_delete_delay_s: 5
